<?php

/**
 * BaseReservaTieneAlojamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idAlojamiento
 * @property integer $idReserva
 * 
 * @method integer                 getIdAlojamiento() Returns the current record's "idAlojamiento" value
 * @method integer                 getIdReserva()     Returns the current record's "idReserva" value
 * @method ReservaTieneAlojamiento setIdAlojamiento() Sets the current record's "idAlojamiento" value
 * @method ReservaTieneAlojamiento setIdReserva()     Sets the current record's "idReserva" value
 * 
 * @package    LaColora
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReservaTieneAlojamiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reserva_tiene_alojamiento');
        $this->hasColumn('idAlojamiento', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('idReserva', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}