<?php

/**
 * BaseEmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idEmpleado
 * @property integer $datosEmpleado
 * @property integer $credenciales
 * @property Credenciales $Credenciales
 * @property DatosPersonales $DatosPersonales
 * @property Doctrine_Collection $OfertaTemporada
 * @property Doctrine_Collection $OfertaPersonalizada
 * 
 * @method integer             getIdEmpleado()          Returns the current record's "idEmpleado" value
 * @method integer             getDatosEmpleado()       Returns the current record's "datosEmpleado" value
 * @method integer             getCredenciales()        Returns the current record's "credenciales" value
 * @method Credenciales        getCredenciales()        Returns the current record's "Credenciales" value
 * @method DatosPersonales     getDatosPersonales()     Returns the current record's "DatosPersonales" value
 * @method Doctrine_Collection getOfertaTemporada()     Returns the current record's "OfertaTemporada" collection
 * @method Doctrine_Collection getOfertaPersonalizada() Returns the current record's "OfertaPersonalizada" collection
 * @method Empleado            setIdEmpleado()          Sets the current record's "idEmpleado" value
 * @method Empleado            setDatosEmpleado()       Sets the current record's "datosEmpleado" value
 * @method Empleado            setCredenciales()        Sets the current record's "credenciales" value
 * @method Empleado            setCredenciales()        Sets the current record's "Credenciales" value
 * @method Empleado            setDatosPersonales()     Sets the current record's "DatosPersonales" value
 * @method Empleado            setOfertaTemporada()     Sets the current record's "OfertaTemporada" collection
 * @method Empleado            setOfertaPersonalizada() Sets the current record's "OfertaPersonalizada" collection
 * 
 * @package    LaColora
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('colora_empleado');
        $this->hasColumn('idEmpleado', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('datosEmpleado', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('credenciales', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Credenciales', array(
             'local' => 'credenciales',
             'foreign' => 'idCredenciales',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DatosPersonales', array(
             'local' => 'datosEmpleado',
             'foreign' => 'idDatosPersonales',
             'onDelete' => 'CASCADE'));

        $this->hasMany('OfertaTemporada', array(
             'local' => 'idEmpleado',
             'foreign' => 'codGerente'));

        $this->hasMany('OfertaPersonalizada', array(
             'local' => 'idEmpleado',
             'foreign' => 'codGerente'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}