<?php

/**
 * BaseTarifa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idTarifa
 * @property integer $idAlojamiento
 * @property date $fechaInicio
 * @property date $fechaFin
 * @property decimal $precioBase
 * @property string $conceptoExtra1
 * @property string $precioExtra1
 * @property string $conceptoExtra2
 * @property string $precioExtra2
 * @property Alojamiento $Alojamiento
 * 
 * @method integer     getIdTarifa()       Returns the current record's "idTarifa" value
 * @method integer     getIdAlojamiento()  Returns the current record's "idAlojamiento" value
 * @method date        getFechaInicio()    Returns the current record's "fechaInicio" value
 * @method date        getFechaFin()       Returns the current record's "fechaFin" value
 * @method decimal     getPrecioBase()     Returns the current record's "precioBase" value
 * @method string      getConceptoExtra1() Returns the current record's "conceptoExtra1" value
 * @method string      getPrecioExtra1()   Returns the current record's "precioExtra1" value
 * @method string      getConceptoExtra2() Returns the current record's "conceptoExtra2" value
 * @method string      getPrecioExtra2()   Returns the current record's "precioExtra2" value
 * @method Alojamiento getAlojamiento()    Returns the current record's "Alojamiento" value
 * @method Tarifa      setIdTarifa()       Sets the current record's "idTarifa" value
 * @method Tarifa      setIdAlojamiento()  Sets the current record's "idAlojamiento" value
 * @method Tarifa      setFechaInicio()    Sets the current record's "fechaInicio" value
 * @method Tarifa      setFechaFin()       Sets the current record's "fechaFin" value
 * @method Tarifa      setPrecioBase()     Sets the current record's "precioBase" value
 * @method Tarifa      setConceptoExtra1() Sets the current record's "conceptoExtra1" value
 * @method Tarifa      setPrecioExtra1()   Sets the current record's "precioExtra1" value
 * @method Tarifa      setConceptoExtra2() Sets the current record's "conceptoExtra2" value
 * @method Tarifa      setPrecioExtra2()   Sets the current record's "precioExtra2" value
 * @method Tarifa      setAlojamiento()    Sets the current record's "Alojamiento" value
 * 
 * @package    LaColora
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarifa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('colora_tarifa');
        $this->hasColumn('idTarifa', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('idAlojamiento', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('fechaInicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fechaFin', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('precioBase', 'decimal', 8, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 8,
             ));
        $this->hasColumn('conceptoExtra1', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('precioExtra1', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('conceptoExtra2', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('precioExtra2', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alojamiento', array(
             'local' => 'idAlojamiento',
             'foreign' => 'idAlojamiento',
             'onDelete' => 'CASCADE'));
    }
}