<?php

/**
 * BaseCredenciales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idCredenciales
 * @property string $usuario
 * @property string $password
 * @property Doctrine_Collection $Cliente
 * @property Doctrine_Collection $Empleado
 * 
 * @method integer             getIdCredenciales() Returns the current record's "idCredenciales" value
 * @method string              getUsuario()        Returns the current record's "usuario" value
 * @method string              getPassword()       Returns the current record's "password" value
 * @method Doctrine_Collection getCliente()        Returns the current record's "Cliente" collection
 * @method Doctrine_Collection getEmpleado()       Returns the current record's "Empleado" collection
 * @method Credenciales        setIdCredenciales() Sets the current record's "idCredenciales" value
 * @method Credenciales        setUsuario()        Sets the current record's "usuario" value
 * @method Credenciales        setPassword()       Sets the current record's "password" value
 * @method Credenciales        setCliente()        Sets the current record's "Cliente" collection
 * @method Credenciales        setEmpleado()       Sets the current record's "Empleado" collection
 * 
 * @package    LaColora
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCredenciales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('colora_credenciales');
        $this->hasColumn('idCredenciales', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('usuario', 'string', 255, array(
             'type' => 'string',
             'minlength' => 8,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'minlength' => 8,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cliente', array(
             'local' => 'idCredenciales',
             'foreign' => 'credenciales'));

        $this->hasMany('Empleado', array(
             'local' => 'idCredenciales',
             'foreign' => 'credenciales'));
    }
}