<?php

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idCliente
 * @property integer $datosCliente
 * @property integer $credenciales
 * @property Credenciales $Credenciales
 * @property DatosPersonales $DatosPersonales
 * @property Doctrine_Collection $Reserva
 * @property Doctrine_Collection $OfertaPersonalizada
 * 
 * @method integer             getIdCliente()           Returns the current record's "idCliente" value
 * @method integer             getDatosCliente()        Returns the current record's "datosCliente" value
 * @method integer             getCredenciales()        Returns the current record's "credenciales" value
 * @method Credenciales        getCredenciales()        Returns the current record's "Credenciales" value
 * @method DatosPersonales     getDatosPersonales()     Returns the current record's "DatosPersonales" value
 * @method Doctrine_Collection getReserva()             Returns the current record's "Reserva" collection
 * @method Doctrine_Collection getOfertaPersonalizada() Returns the current record's "OfertaPersonalizada" collection
 * @method Cliente             setIdCliente()           Sets the current record's "idCliente" value
 * @method Cliente             setDatosCliente()        Sets the current record's "datosCliente" value
 * @method Cliente             setCredenciales()        Sets the current record's "credenciales" value
 * @method Cliente             setCredenciales()        Sets the current record's "Credenciales" value
 * @method Cliente             setDatosPersonales()     Sets the current record's "DatosPersonales" value
 * @method Cliente             setReserva()             Sets the current record's "Reserva" collection
 * @method Cliente             setOfertaPersonalizada() Sets the current record's "OfertaPersonalizada" collection
 * 
 * @package    LaColora
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('colora_cliente');
        $this->hasColumn('idCliente', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('datosCliente', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('credenciales', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Credenciales', array(
             'local' => 'credenciales',
             'foreign' => 'idCredenciales',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DatosPersonales', array(
             'local' => 'datosCliente',
             'foreign' => 'idDatosPersonales',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Reserva', array(
             'local' => 'idCliente',
             'foreign' => 'cliente'));

        $this->hasMany('OfertaPersonalizada', array(
             'local' => 'idCliente',
             'foreign' => 'codCliente'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}