<?php

/**
 * BaseReserva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idReserva
 * @property integer $cliente
 * @property decimal $importe
 * @property decimal $fianzaDepositada
 * @property timestamp $fechaSalida
 * @property timestamp $fechaLlegada
 * @property enum $estado
 * @property integer $codOfertaTemporada
 * @property string $codOfertaPersonalizada
 * @property integer $realizada_por
 * @property Cliente $Cliente
 * @property DatosPersonales $DatosPersonales
 * @property OfertaTemporada $OfertaTemporada
 * @property OfertaPersonalizada $OfertaPersonalizada
 * @property Doctrine_Collection $Reservas
 * @property Doctrine_Collection $Factura
 * 
 * @method integer             getIdReserva()              Returns the current record's "idReserva" value
 * @method integer             getCliente()                Returns the current record's "cliente" value
 * @method decimal             getImporte()                Returns the current record's "importe" value
 * @method decimal             getFianzaDepositada()       Returns the current record's "fianzaDepositada" value
 * @method timestamp           getFechaSalida()            Returns the current record's "fechaSalida" value
 * @method timestamp           getFechaLlegada()           Returns the current record's "fechaLlegada" value
 * @method enum                getEstado()                 Returns the current record's "estado" value
 * @method integer             getCodOfertaTemporada()     Returns the current record's "codOfertaTemporada" value
 * @method string              getCodOfertaPersonalizada() Returns the current record's "codOfertaPersonalizada" value
 * @method integer             getRealizadaPor()           Returns the current record's "realizada_por" value
 * @method Cliente             getCliente()                Returns the current record's "Cliente" value
 * @method DatosPersonales     getDatosPersonales()        Returns the current record's "DatosPersonales" value
 * @method OfertaTemporada     getOfertaTemporada()        Returns the current record's "OfertaTemporada" value
 * @method OfertaPersonalizada getOfertaPersonalizada()    Returns the current record's "OfertaPersonalizada" value
 * @method Doctrine_Collection getReservas()               Returns the current record's "Reservas" collection
 * @method Doctrine_Collection getFactura()                Returns the current record's "Factura" collection
 * @method Reserva             setIdReserva()              Sets the current record's "idReserva" value
 * @method Reserva             setCliente()                Sets the current record's "cliente" value
 * @method Reserva             setImporte()                Sets the current record's "importe" value
 * @method Reserva             setFianzaDepositada()       Sets the current record's "fianzaDepositada" value
 * @method Reserva             setFechaSalida()            Sets the current record's "fechaSalida" value
 * @method Reserva             setFechaLlegada()           Sets the current record's "fechaLlegada" value
 * @method Reserva             setEstado()                 Sets the current record's "estado" value
 * @method Reserva             setCodOfertaTemporada()     Sets the current record's "codOfertaTemporada" value
 * @method Reserva             setCodOfertaPersonalizada() Sets the current record's "codOfertaPersonalizada" value
 * @method Reserva             setRealizadaPor()           Sets the current record's "realizada_por" value
 * @method Reserva             setCliente()                Sets the current record's "Cliente" value
 * @method Reserva             setDatosPersonales()        Sets the current record's "DatosPersonales" value
 * @method Reserva             setOfertaTemporada()        Sets the current record's "OfertaTemporada" value
 * @method Reserva             setOfertaPersonalizada()    Sets the current record's "OfertaPersonalizada" value
 * @method Reserva             setReservas()               Sets the current record's "Reservas" collection
 * @method Reserva             setFactura()                Sets the current record's "Factura" collection
 * 
 * @package    LaColora
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReserva extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('colora_reserva');
        $this->hasColumn('idReserva', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('cliente', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('importe', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 9,
             ));
        $this->hasColumn('fianzaDepositada', 'decimal', 9, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'length' => 9,
             ));
        $this->hasColumn('fechaSalida', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('fechaLlegada', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('estado', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'o',
              1 => 'l',
              2 => 'p',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('codOfertaTemporada', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'default' => 0,
             ));
        $this->hasColumn('codOfertaPersonalizada', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('realizada_por', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'cliente',
             'foreign' => 'idCliente',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DatosPersonales', array(
             'local' => 'realizada_por',
             'foreign' => 'idDatosPersonales',
             'onDelete' => 'CASCADE'));

        $this->hasOne('OfertaTemporada', array(
             'local' => 'codOfertaTemporada',
             'foreign' => 'idOfertaTemporada',
             'onDelete' => 'CASCADE'));

        $this->hasOne('OfertaPersonalizada', array(
             'local' => 'codOfertaPersonalizada',
             'foreign' => 'idOfertaPersonalizada',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Alojamiento as Reservas', array(
             'refClass' => 'ReservaTieneAlojamiento',
             'local' => 'idReserva',
             'foreign' => 'idAlojamiento'));

        $this->hasMany('Factura', array(
             'local' => 'idReserva',
             'foreign' => 'idReserva'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}