<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/10 20:33:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=LaColora',
  'username' => 'colora',
  'password' => 'colora',
  'name' => 'doctrine',
)),);
